var canvas;
var ctx;
var unit = 20;
window.onload = init;
function init() {

    canvas = document.getElementById("myCanvas");
    ctx = canvas.getContext("2d");
    ctx.fillStyle = "black";
    ctx.fillRect(5 * unit, 0, 4 * unit, 1 * unit);
    ctx.fillRect(4 * unit, 1 * unit, 1 * unit, 1 * unit );
    ctx.fillRect(3 * unit, 2 * unit, 1 * unit, 1 * unit);
    ctx.fillRect(2* unit,3* unit,2* unit,1* unit);
    ctx.fillRect(1 * unit, 4 * unit, 1 * unit, 1 * unit );
    ctx.fillRect(0 * unit, 5 * unit, 1 * unit, 4 * unit );
    ctx.fillRect(1 * unit, 9 * unit, 2 * unit, 1 * unit );
    ctx.fillRect(9* unit, 1* unit,1* unit,1* unit);
    ctx.fillRect(10* unit,2* unit,1* unit,2* unit);
    ctx.fillRect(11* unit,4* unit,1* unit,3* unit);
    ctx.fillRect(12* unit,7* unit,1* unit,2* unit);
    ctx.fillRect(13* unit,9* unit,1* unit,2* unit);
    ctx.fillRect(14* unit,11* unit,1* unit,3* unit);
    ctx.fillRect(15* unit,14* unit,2* unit,1* unit);
    ctx.fillRect(17* unit,11* unit,1* unit,3* unit);
    ctx.fillRect(19* unit,11* unit,1* unit,3* unit);
    ctx.fillRect(18* unit,14* unit,1* unit,2* unit);
    ctx.fillRect(17* unit,16* unit,1* unit,1* unit);
    ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    ctx.fillStyle = "rgb(208,56,0)";
    ctx.fillRect(5* unit,1* unit, 1 * unit, 1* unit);
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
    // ctx.fillRect();
}

